############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "Project"
url = "project/"
weight = 2

[[main]]
name = "Blog"
url = "blog/"
weight = 3

[[main]]
name = "About"
url = "about/"
weight = 4

# footer menu
[[footer]]
name = "Newsletter"
url = "newsletter/"
weight = 1

# [[footer]]
# name = "Contact us"
# url = "contact/"
# weight = 2

# [[footer]]
# name = "Contact us"
# url = "contact/"
# weight = 2

[[footer]]
name = "Documents"
url = "documents/"
weight = 2

# [[footer]]
# name = "About"
# url = "about/"
# weight = 2