############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "About"
url = "about/"
weight = 2

#[[main]]
#name = "Elements"
#url = "elements/"
#weight = 3

[[main]]
name = "Blog"
url = "blog/"
weight = 3

[[main]]
weight = 5
name = "More"
hasChildren = true

#[[main]]
#parent = "More"
#name = "Blog"
#url = "blog/"

#Criar newsletter e mudar o url 
[[main]]
parent = "More"
name = "Newsletter"
url = "newsletter/"

#Mudar url
[[main]]
parent = "More"
name = "Team"
url = "authors/"

#[[main]]
#parent = "More"
#name = "Categories"
#url = "categories/"

#[[main]]
#parent = "More"
#name = "404 Page"
#url = "404/"


# footer menu
[[footer]]
name = "About"
url = "about/"
weight = 1

#[[footer]]
#name = "Elements"
#url = "elements/"
#weight = 2

[[footer]]
name = "Newsletter"
url = "contact/"
weight = 2

[[footer]]
name = "Privacy Policy"
url = "privacy-policy/"
weight = 3
